config/routes.rb
Rails.application.routes.draw do
  resources :post_comments
  resources :posts
  get 'blog/index'

  get 'blog/show'

  resources :caurusel_images
  resources :products
  get 'admin/index'
  get 'main/blog' => 'main#blog', as: "blog"
  get 'main/index'

   root 'main#index'

end

app/views/shared-admin/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/admin/index">ADMIN PAGE</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li><a href="#">Link</a></li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">add items/images <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "caurusel", caurusel_images_path %></li>
            <li><%= link_to "products for buying", products_path %></li>
            <li><a href="#">products for sale</a></li>
            <li><%= link_to 'blog & news', posts_path %></li>
          </ul>
        </li>
        <li><%= link_to "show main page", root_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>