config/routes.rb
Rails.application.routes.draw do
  resources :post_comments
  resources :posts
  get 'blog/index'

  get 'blog/show'

  resources :caurusel_images
  resources :products
  get 'admin/index'
  get 'main/blog' => 'main#blog', as: "blog"
  get 'main/index'

   root 'main#index'

end

app/views/shared/_advantage.html.erb
  <div id="content">

    <div class="container">
      <div class="col-md-12">
        <div id="main-slider">

          <% @caurusel_img.each do |img| %>

          <div class="item">
             <%= image_tag img.img, class: "img-responsive" %>
          </div>

              <% end %>

        </div>
        <!-- /#main-slider -->
      </div>
    </div>

<!-- *** ADVANTAGES HOMEPAGE ***
_________________________________________________________ -->
<div id="advantages">

  <div class="container">
    <div class="same-height-row">
      <div class="col-sm-4">
        <div class="box same-height clickable">
          <div class="icon"><i class="fa fa-heart"></i>
          </div>

          <h3><a href="#">We love our customers</a></h3>
          <p>We are known to provide best possible service ever</p>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="box same-height clickable">
          <div class="icon"><i class="fa fa-tags"></i>
          </div>

          <h3><a href="#">Best prices</a></h3>
          <p>You can check that the height of the boxes adjust when longer text like this one is used in one of them.</p>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="box same-height clickable">
          <div class="icon"><i class="fa fa-thumbs-up"></i>
          </div>

          <h3><a href="#">100% satisfaction guaranteed</a></h3>
          <p>Free returns on everything for 3 months.</p>
        </div>
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

</div>
<!-- /#advantages -->

<!-- *** ADVANTAGES END *** -->

app/views/shared/_blog.html.erb
<!-- *** BLOG HOMEPAGE ***
_________________________________________________________ -->

<div class="box text-center" data-animate="fadeInUp">
  <div class="container">
    <div class="col-md-12">
      <h3 class="text-uppercase">What's new?</h3>


     <p class="read-more"> <%= link_to "ALL NEWS", blog_index_path,  class: "btn btn-primary" %> </p>

    </div>
  </div>
</div>

<div class="container">

  <div class="col-md-12" data-animate="fadeInUp">

    <div id="blog-homepage" class="row">
     <% @posts.each do |post| %>
      <div class="col-sm-6">
        <div class="post">
          <h4><%= link_to post.title_1 , post %></h4>
          <p class="author-category">By <strong>admin </strong> of <a href=""> WeBuyGoods</a>
          </p>
          <hr>
          <p class="intro"><%= post.text %></p>
          <p class="read-more">
            <%= link_to "Continue reading" , blog_show_path(:id => post.id), class: 'btn btn-primary' %>
          </p>
        </div>
      </div>
    <% end %>


      </div>

    </div>
    <!-- /#blog-homepage -->
  </div>
</div>
<!-- /.container -->

<!-- *** BLOG HOMEPAGE END *** -->


</div>
<!-- /#content -->

app/views/shared/_copywrite.html.erb
<!-- *** COPYRIGHT ***
_________________________________________________________ -->
<div id="copyright">
  <div class="container">
    <div class="col-md-6">
      <p class="pull-left">© 2015 WeBuyGoods.com</p>

    </div>
    <div class="col-md-6">
      <p class="pull-right">Template by <a href="http://www.bootstrapious.com">Responsive Templates</a> with support from <a href="http://kakusei.cz">Designové předměty</a>
        <!-- Not removing these links is part of the licence conditions of the template. Thanks for understanding :) -->
      </p>
    </div>
  </div>
</div>
<!-- *** COPYRIGHT END *** -->

app/views/shared/_footer.html.erb
<!-- *** FOOTER ***
 _________________________________________________________ -->
<div id="footer" data-animate="fadeInUp">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <h4>Pages</h4>

        <ul>
          <li><a href="text.html">About us</a>
          </li>
          <li><a href="text.html">Terms and conditions</a>
          </li>
          <li><a href="faq.html">FAQ</a>
          </li>
          <li><a href="contact.html">Contact us</a>
          </li>
        </ul>

        <hr>

        <h4>User section</h4>

        <ul>
          <li><a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
          </li>
          <li><a href="register.html">Regiter</a>
          </li>
        </ul>

        <hr class="hidden-md hidden-lg hidden-sm">

      </div>
      <!-- /.col-md-3 -->

      <div class="col-md-3 col-sm-6">

        <h4>Top categories</h4>

        <h5>Men</h5>

        <ul>
          <li><a href="category.html">T-shirts</a>
          </li>
          <li><a href="category.html">Shirts</a>
          </li>
          <li><a href="category.html">Accessories</a>
          </li>
        </ul>

        <h5>Ladies</h5>
        <ul>
          <li><a href="category.html">T-shirts</a>
          </li>
          <li><a href="category.html">Skirts</a>
          </li>
          <li><a href="category.html">Pants</a>
          </li>
          <li><a href="category.html">Accessories</a>
          </li>
        </ul>

        <hr class="hidden-md hidden-lg">

      </div>
      <!-- /.col-md-3 -->

      <div class="col-md-3 col-sm-6">

        <h4>Where to find us</h4>

        <p><strong>We Buy Goods, inc</strong>
          <br>8710 Lefferts Blvd
          <br>Richmond Hill
          <br>Queens
          <br>New York, 11418
          <br>
          <strong>USA</strong>
        </p>

        <a href="contact.html">Go to contact page</a>

        <hr class="hidden-md hidden-lg">

      </div>
      <!-- /.col-md-3 -->



      <div class="col-md-3 col-sm-6">

        <h4>Get the news</h4>

        <p class="text-muted">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>

        <form>
          <div class="input-group">

            <input type="text" class="form-control">

                                <span class="input-group-btn">

			    <button class="btn btn-default" type="button">Subscribe!</button>

			</span>

          </div>
          <!-- /input-group -->
        </form>

        <hr>

        <h4>Stay in touch</h4>

        <p class="social">
          <a href="#" class="facebook external" data-animate-hover="shake"><i class="fa fa-facebook"></i></a>
          <a href="#" class="twitter external" data-animate-hover="shake"><i class="fa fa-twitter"></i></a>
          <a href="#" class="instagram external" data-animate-hover="shake"><i class="fa fa-instagram"></i></a>
          <a href="#" class="gplus external" data-animate-hover="shake"><i class="fa fa-google-plus"></i></a>
          <a href="#" class="email external" data-animate-hover="shake"><i class="fa fa-envelope"></i></a>
        </p>


      </div>
      <!-- /.col-md-3 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
</div>
<!-- /#footer -->

<!-- *** FOOTER END *** -->

app/views/shared/_head.html.erb
<!--RAILS-->

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

<!--END RAILS-->

<meta charset="utf-8">
<meta name="robots" content="all,follow">
<meta name="googlebot" content="index,follow,snippet,archive">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Obaju e-commerce template">
<meta name="author" content="Ondrej Svestka | ondrejsvestka.cz">
<meta name="keywords" content="">



<meta name="keywords" content="">

<link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>

<!-- styles -->
<link href="css/font-awesome.css" rel="stylesheet">
<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/animate.min.css" rel="stylesheet">
<link href="css/owl.carousel.css" rel="stylesheet">
<link href="css/owl.theme.css" rel="stylesheet">

<!-- theme stylesheet -->
<link href="css/style.default.css" rel="stylesheet" id="theme-stylesheet">

<!-- your stylesheet with modifications -->
<link href="css/custom.css" rel="stylesheet">

<script src="js/respond.min.js"></script>

<link rel="shortcut icon" href="favicon.png">

app/views/shared/_inspired.html.erb
<!-- *** GET INSPIRED ***
_________________________________________________________ -->
<div class="container" data-animate="fadeInUpBig">
  <div class="col-md-12">
    <div class="box slideshow">
      <h3>Get Inspired</h3>
      <p class="lead">Get the inspiration from our world class designers</p>
      <div id="get-inspired" class="owl-carousel owl-theme">
        <div class="item">
          <a href="#">
            <img src="img/getinspired1.jpg" alt="Get inspired" class="img-responsive">
          </a>
        </div>
        <div class="item">
          <a href="#">
            <img src="img/getinspired2.jpg" alt="Get inspired" class="img-responsive">
          </a>
        </div>
        <div class="item">
          <a href="#">
            <img src="img/getinspired3.jpg" alt="Get inspired" class="img-responsive">
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- *** GET INSPIRED END *** -->

app/views/shared/_navbar.html.erb
<!-- *** NAVBAR ***
_________________________________________________________ -->

<div class="navbar navbar-default yamm" role="navigation" id="navbar">
  <div class="container">
    <div class="navbar-header">

      <a class="navbar-brand home" href="/" data-animate-hover="bounce">
        <img src="/img/logo.png" alt="Obaju logo" class="hidden-xs">
        <img src="/img/logo-small.png" alt="Obaju logo" class="visible-xs"><span class="sr-only">WeBuyGoods - go to homepage</span>
      </a>
      <div class="navbar-buttons">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
          <span class="sr-only">Toggle navigation</span>
          <i class="fa fa-align-justify"></i>
        </button>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#search">
          <span class="sr-only">Toggle search</span>
          <i class="fa fa-search"></i>
        </button>
        <a class="btn btn-default navbar-toggle" href="basket.html">
          <i class="fa fa-shopping-cart"></i>  <span class="hidden-xs">3 items in cart</span>
        </a>
      </div>
    </div>
    <!--/.navbar-header -->

    <div class="navbar-collapse collapse" id="navigation">

      <ul class="nav navbar-nav navbar-left">
        <li class="active"><a href="index.html">Home</a>
        </li>
        <li class="dropdown yamm-fw">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">WE BUY <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <div class="yamm-content">
                <div class="row">
                  <div class="col-sm-3">
                    <h5>Electronics</h5>
                    <ul>
                      <li><a href="category.html">iPhones/Phones</a>
                      </li>
                      <li><a href="category.html">iPads/Tablets</a>
                      </li>
                      <li><a href="category.html">MacBooks/Laptops</a>
                      </li>
                      <li><a href="category.html">Game Consoles</a>
                      </li>
                      <li><a href="category.html">Canon/Nikon/Leica Cameras</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>Handbags</h5>
                    <ul>
                      <li><a href="category.html">Louis Vuitton</a>
                      </li>
                      <li><a href="category.html">Chanel</a>
                      </li>
                      <li><a href="category.html">Hermes</a>
                      </li>
                      <li><a href="category.html">Other handbags</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>Watches</h5>
                    <ul>
                      <li><a href="category.html">Rolex</a>
                      </li>
                      <li><a href="category.html">Citizen</a>
                      </li>
                      <li><a href="category.html">Hiking shoes</a>
                      </li>
                      <li><a href="category.html">Casual</a>
                      </li>
                      <li><a href="category.html">Hiking shoes</a>
                      </li>
                      <li><a href="category.html">Casual</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>Watches</h5>
                    <ul>
                      <li><a href="category.html">Rolex</a>
                      </li>
                      <li><a href="category.html">Citizen</a>
                      </li>
                      <li><a href="category.html">Brithing</a>
                      </li>
                    </ul>
                    <h5>Other Items</h5>
                    <ul>
                      <li><a href="category.html">Gold</a>
                      </li>
                      <li><a href="category.html">Silver</a>
                      </li>
                      <li><a href="category.html">Diamands</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <!-- /.yamm-content -->
            </li>
          </ul>
        </li>

        <li class="dropdown yamm-fw">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">WE SELL <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <div class="yamm-content">
                <div class="row">
                  <div class="col-sm-3">
                    <h5>Clothing</h5>
                    <ul>
                      <li><a href="category.html">T-shirts</a>
                      </li>
                      <li><a href="category.html">Shirts</a>
                      </li>
                      <li><a href="category.html">Pants</a>
                      </li>
                      <li><a href="category.html">Accessories</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>Shoes</h5>
                    <ul>
                      <li><a href="category.html">Trainers</a>
                      </li>
                      <li><a href="category.html">Sandals</a>
                      </li>
                      <li><a href="category.html">Hiking shoes</a>
                      </li>
                      <li><a href="category.html">Casual</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>Accessories</h5>
                    <ul>
                      <li><a href="category.html">Trainers</a>
                      </li>
                      <li><a href="category.html">Sandals</a>
                      </li>
                      <li><a href="category.html">Hiking shoes</a>
                      </li>
                      <li><a href="category.html">Casual</a>
                      </li>
                      <li><a href="category.html">Hiking shoes</a>
                      </li>
                      <li><a href="category.html">Casual</a>
                      </li>
                    </ul>
                    <h5>Looks and trends</h5>
                    <ul>
                      <li><a href="category.html">Trainers</a>
                      </li>
                      <li><a href="category.html">Sandals</a>
                      </li>
                      <li><a href="category.html">Hiking shoes</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <div class="banner">
                      <a href="#">
                        <img src="img/banner.jpg" class="img img-responsive" alt="">
                      </a>
                    </div>
                    <div class="banner">
                      <a href="#">
                        <img src="img/banner2.jpg" class="img img-responsive" alt="">
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.yamm-content -->
            </li>
          </ul>
        </li>

        <li class="dropdown yamm-fw">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">CONTACTS <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <div class="yamm-content">
                <div class="row">
                  <div class="col-sm-3">
                    <h5>Shop</h5>
                    <ul>
                      <li><a href="index.html">Homepage</a>
                      </li>
                      <li><a href="category.html">Category - sidebar left</a>
                      </li>
                      <li><a href="category-right.html">Category - sidebar right</a>
                      </li>
                      <li><a href="category-full.html">Category - full width</a>
                      </li>
                      <li><a href="detail.html">Product detail</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>User</h5>
                    <ul>
                      <li><a href="register.html">Register / login</a>
                      </li>
                      <li><a href="customer-orders.html">Orders history</a>
                      </li>
                      <li><a href="customer-order.html">Order history detail</a>
                      </li>
                      <li><a href="customer-wishlist.html">Wishlist</a>
                      </li>
                      <li><a href="customer-account.html">Customer account / change password</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>Order process</h5>
                    <ul>
                      <li><a href="basket.html">Shopping cart</a>
                      </li>
                      <li><a href="checkout1.html">Checkout - step 1</a>
                      </li>
                      <li><a href="checkout2.html">Checkout - step 2</a>
                      </li>
                      <li><a href="checkout3.html">Checkout - step 3</a>
                      </li>
                      <li><a href="checkout4.html">Checkout - step 4</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>Pages and blog</h5>
                    <ul>
                      <li><a href="blog.html">Blog listing</a>
                      </li>
                      <li><a href="post.html">Blog Post</a>
                      </li>
                      <li><a href="faq.html">FAQ</a>
                      </li>
                      <li><a href="text.html">Text page</a>
                      </li>
                      <li><a href="text-right.html">Text page - right sidebar</a>
                      </li>
                      <li><a href="404.html">404 page</a>
                      </li>
                      <li><a href="contact.html">Contact</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <!-- /.yamm-content -->
            </li>
          </ul>
        </li>
      </ul>

    </div>
    <!--/.nav-collapse -->

    <div class="navbar-buttons">

      <div class="navbar-collapse collapse right" id="basket-overview">
        <a href="basket.html" class="btn btn-primary navbar-btn"><i class="fa fa-shopping-cart"></i><span class="hidden-sm"> 0 items in your cart </span></a>
      </div>
      <!--/.nav-collapse -->

      <div class="navbar-collapse collapse right" id="search-not-mobile">
        <button type="button" class="btn navbar-btn btn-primary" data-toggle="collapse" data-target="#search">
          <span class="sr-only">Toggle search</span>
          <i class="fa fa-search"></i>
        </button>
      </div>

    </div>

    <div class="collapse clearfix" id="search">

      <form class="navbar-form" role="search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search">
                        <span class="input-group-btn">

			<button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>

		    </span>
        </div>
      </form>

    </div>
    <!--/.nav-collapse -->

  </div>
  <!-- /.container -->
</div>
<!-- /#navbar -->

<!-- *** NAVBAR END *** -->

app/views/shared/_products.html.erb
<!-- *** HOT PRODUCT SLIDESHOW ***
 _________________________________________________________ -->
<div id="hot">

  <div class="box">
    <div class="container">
      <div class="col-md-12">
        <h2>NEW ITEMS/DISCOUNTS</h2>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="product-slider">


      <% @products.each do |product| %>

          <div class="item">
            <div class="product">

              <div class="flip-container">
                <div class="flipper">


                  <div class="front">
                    <%= link_to(product) do %>
                        <%= image_tag product.first_img , class: 'img-responsive' %>
                    <% end  %>
                  </div>
                  <div class="back">
                    <%= link_to(product) do %>
                        <%= image_tag product.second_img , class: 'img-responsive' %>
                    <% end  %>
                  </div>
                </div>
              </div>

              <%= link_to(product, class: 'invisible') do %>
                  <%= image_tag product.first_img , class: 'img-responsive' %>
              <% end  %>
              <div class="text">
                <h3><%= link_to product.text, product %></h3>
                <p class="price"> <strong> UP TO <%= product.price %>$</strong> </p>
              </div>
              <!-- /.text -->
            </div>
            <!-- /.product -->
          </div>
      <% end  %>

    </div>
    <!-- /.product-slider -->
  </div>
  <!-- /.container -->

</div>
<!-- /#hot -->

<!-- *** HOT END *** -->

app/views/shared/_scripts.html.erb
<!-- *** SCRIPTS TO INCLUDE ***
_________________________________________________________ -->
<script src="js/jquery-1.11.0.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.cookie.js"></script>
<script src="js/waypoints.min.js"></script>
<script src="js/modernizr.js"></script>
<script src="js/bootstrap-hover-dropdown.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/front.js"></script>

app/views/shared/_tapbar.html.erb
<!-- *** TOPBAR ***
 _________________________________________________________ -->
<div id="top">
  <div class="container">
    <div class="col-md-6 offer" data-animate="fadeInDown">
      <a href="tel:+1-718-846-1600"> For more info </a> <a href="tel:+1-718-846-1600" class="btn btn-success btn-sm" data-animate-hover="shake"> <i class="fa fa-phone"></i> +1 (718) 846 1660  </a>
    </div>
    <div class="col-md-6" data-animate="fadeInDown">
      <ul class="menu hidden-xs">
        <li><%= link_to 'admin page', admin_index_path %>
        </li>
        <li><a href="register.html">Careers</a>
        </li>
        <li><a href="contact.html">Contact</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog modal-sm">

      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="Login">Customer login</h4>
        </div>
        <div class="modal-body">
          <form action="customer-orders.html" method="post">
            <div class="form-group">
              <input type="text" class="form-control" id="email-modal" placeholder="email">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="password-modal" placeholder="password">
            </div>

            <p class="text-center">
              <button class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
            </p>

          </form>

          <p class="text-center text-muted">Not registered yet?</p>
          <p class="text-center text-muted"><a href="register.html"><strong>Register now</strong></a>! It is easy and done in 1&nbsp;minute and gives you access to special discounts and much more!</p>

        </div>
      </div>
    </div>
  </div>

</div>

<!-- *** TOP BAR END *** -->